### ISSUE TITLE
Distribute as a snap?

### ISSUE THREAD

**Issue by artivis** [gotify/cli#48]
Hi,

Would you consider distributing this CLI tool as a [snap](https://snapcraft.io/about)? 
This would make it much simpler to install on a bunch of distros, e.g.

```bash
snap install gotify-cli
...
gotify-cli push "Hello World"
```

I've worked out a minimal snapcraft yaml file (assuming it is included in this repo as `snap/snapcraft.yaml`):

```yaml
name: gotify-cli
summary: A command line interface for pushing messages to gotify/server.
description: |
  Gotify-CLI is a command line client for pushing messages to gotify/server.

version: git
grade: stable
base: core20

confinement: strict

apps:
  gotify-cli:
    command: bin/cli
    plugs: [network]

parts:
  gotify-cli:
    plugin: go
    source: .
```

This was enough for me to build it locally, install it and test the `init/config/push` functionalities. The `version` command only spits `unknown`s tho. Furthermore some of the proposed path for the config file are most likely not exposed by default to the snap.
